nohup ./run_scripts/treat_simu_noacc/run_desktop_P04.sh > outputs/2_treat_simu_noacc/outlogs/out_P04.log &
nohup ./run_scripts/treat_simu_noacc/run_desktop_P06.sh > outputs/2_treat_simu_noacc/outlogs/out_P06.log &
nohup ./run_scripts/treat_simu_noacc/run_desktop_P08.sh > outputs/2_treat_simu_noacc/outlogs/out_P08.log &
nohup ./run_scripts/treat_simu_noacc/run_desktop_P10.sh > outputs/2_treat_simu_noacc/outlogs/out_P10.log &
nohup ./run_scripts/treat_simu_noacc/run_desktop_P11.sh > outputs/2_treat_simu_noacc/outlogs/out_P11.log &
nohup ./run_scripts/treat_simu_noacc/run_desktop_P13.sh > outputs/2_treat_simu_noacc/outlogs/out_P13.log &
nohup ./run_scripts/treat_simu_noacc/run_desktop_P16.sh > outputs/2_treat_simu_noacc/outlogs/out_P16.log &
nohup ./run_scripts/treat_simu_noacc/run_desktop_P17.sh > outputs/2_treat_simu_noacc/outlogs/out_P17.log &
nohup ./run_scripts/treat_simu_noacc/run_desktop_P19.sh > outputs/2_treat_simu_noacc/outlogs/out_P19.log &
nohup ./run_scripts/treat_simu_noacc/run_desktop_P20.sh > outputs/2_treat_simu_noacc/outlogs/out_P20.log &